version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./backend/.env

  register_service:
    build:
      context: backend
      dockerfile: services/registerservice/Dockerfile
    container_name: register_service
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - MICRO_REGISTRY=mdns
    depends_on:
      - db

  login_service:
    build:
      context: backend
      dockerfile: services/loginservice/Dockerfile
    container_name: login_service
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - MICRO_REGISTRY=mdns
    depends_on:
      - db

  envoy:
    image: envoyproxy/envoy:v1.20-latest
    ports:
      - '8081:8081'
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./backend/services/combined.pb:/proto/combined.pb
    depends_on:
      - register_service
      - login_service

  frontend:
    build:
      context: frontend
    container_name: frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - envoy
