version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./backend/.env

  register_service:
    build:
      context: backend
      dockerfile: cmd/service/register/Dockerfile
    container_name: register_service
    restart: always
    ports:
      - "127.0.0.1:3001:80"
    env_file:
      - ./backend/.env

  login_service:
    build:
      context: backend
      dockerfile: cmd/service/login/Dockerfile
    container_name: login_service
    restart: always
    ports:
      - "127.0.0.1:3002:80"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: frontend
    container_name: frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
