version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./backend/.env

  frontend_proxy:
    build:
      context: backend
      dockerfile: services/frontend/Dockerfile
    container_name: frontend_proxy
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  login_service:
    build:
      context: backend
      dockerfile: services/login/Dockerfile
    container_name: login_service
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  register_service:
    build:
      context: backend
      dockerfile: services/register/Dockerfile
    container_name: register_service
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: frontend
    container_name: frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - frontend_proxy
      - login_service
      - register_service
  
  go-micro-dashboard:
    image: xpunch/go-micro-dashboard:latest
    container_name: micro-dashboard
    ports:
      - "127.0.0.1:3001:8082"
    env_file:
      - ./backend/.env
