mode: production

database:
  name: kioku-database
  containerName: postgres

  image: postgres
  tag: latest

  replicaCount: 1

  port: 5432

  size: 10Gi
  mountPath: /mnt/data

  secret:
    name: kioku-database-secret

frontend:
  name: kioku-frontend
  image: ghcr.io/kioku-project/kioku_frontend
  tag: prod
  port: 80
  containerPort: 3000

  httpPath: /

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

frontend_proxy:
  name: kioku-frontend-proxy
  image: ghcr.io/kioku-project/kioku_frontend_proxy
  tag: prod
  httpPath: /api

  keySecret: frontend-proxy-key-secret

  port: 80
  containerPort: 80

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50


login:
  name: kioku-login
  image: ghcr.io/kioku-project/kioku_login
  tag: prod

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

register:
  name: kioku-register
  image: ghcr.io/kioku-project/kioku_register
  tag: prod

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50


