mode: production

database:
  name: kioku-database
  containerName: postgres

  image: postgres
  tag: latest

  replicaCount: 1

  port: 5432

  size: 10Gi
  mountPath: /mnt/data

  secret:
    name: kioku-database-secret

frontend:
  name: kioku-frontend
# ghcr.io/kioku-project/kioku_frontend
  image: ghcr.io/kioku-project/kioku_frontend
  tag: latest
  port: 80
  containerPort: 3000

  httpPath: /

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

login:
  name: kioku-login
# ghcr.io/kioku-project/kioku_login
  image: ghcr.io/kioku-project/kioku_login
  tag: latest
  port: 80

  httpPath: /api/login

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

register:
  name: kioku-register
# ghcr.io/kioku-project/kioku_register
  image: ghcr.io/kioku-project/kioku_register
  tag: latest
  port: 80

  httpPath: /api/register

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50


