---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: endpoint-ingress
  labels:
    app: nginx
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: app.kioku.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kioku-frontend-service
                port:
                  number: 8082
          - path: /api/login
            pathType: Prefix
            backend:
              service:
                name: kioku-login-service
                port:
                  number: 8084
          - path: /api/register
            pathType: Prefix
            backend:
              service:
                name: kioku-register-service
                port:
                  number: 8084
          - path: /hello
            pathType: Exact
            backend:
              service:
                name: hello-world-service
                port:
                  number: 8083