---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: endpoint-ingress
  labels:
    app: nginx
spec:
  rules:
    - host: app.kioku.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kioku-frontend-service
                port:
                  number: 8082
          - path: /hello
            pathType: Exact
            backend:
              service:
                name: hello-world-service
                port:
                  number: 8081