---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kioku-login-deployment
  labels:
    app: kioku-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kioku-login
  template:
    metadata:
      labels:
        app: kioku-login
    spec:
      containers:
      - name: kioku-login
        image: ghcr.io/kioku-project/kioku_login
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - secretRef:
              name: database-secret

---
apiVersion: v1
kind: Service
metadata:
  name: kioku-login-service
spec:
  selector:
    app: kioku-login
  ports:
    - port: 8084
      targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-kioku-login-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: kioku-login-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50