---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kioku-register-deployment
  labels:
    app: kioku-register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kioku-register
  template:
    metadata:
      labels:
        app: kioku-register
    spec:
      containers:
      - name: kioku-register
        image: ghcr.io/kioku-project/kioku_register
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - secretRef:
              name: database-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kioku-register-service
spec:
  selector:
    app: kioku-register
  ports:
    - port: 8084
      targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-kioku-register-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: kioku-register-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50