---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginservice
  labels:
    app: loginservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginservice
  template:
    metadata:
      labels:
        app: loginservice
    spec:
      containers:
      - name: loginservice
        securityContext:
          allowPrivilegeEscalation: false
        image: loginservice:latest
        envFrom:
        - configMapRef:
            name: loginservice-env
        readinessProbe:
          grpc:
            port: 41888
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          grpc:
            port: 41888
          initialDelaySeconds: 10
          timeoutSeconds: 5
