---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: endpoint-ingress
  labels:
    app: nginx
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.frontend.httpPath }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.frontend.name }}-service"
                port:
                  number: {{ .Values.frontend.port }}
          - path: {{ .Values.frontend_proxy.httpPath }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.frontend_proxy.name }}-service"
                port:
                  number: {{ .Values.frontend_proxy.port }}