apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend_proxy.keySecret }}
  labels:
    {{- include "kioku.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_PRIVATE_KEY: "Base64 encoded private key"