---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.register.name }}-deployment"
  labels:
    {{- include "kioku.register.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kioku.register.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kioku.register.labels" . | nindent 8 }}
    spec:
      serviceAccountName: go-micro
      containers:
      - name: {{ .Values.register.name }}
        image: "{{ .Values.register.image }}:{{ .Values.register.tag }}"
      {{ if eq .Values.mode "production" }}
        imagePullPolicy: Always
      {{ else }}
        imagePullPolicy: Never
      {{ end }}
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 200m
            memory: 200M
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PORT
            value: "8080"
        envFrom:
          - secretRef:
              name: {{ .Values.database.secret.name }}
          - configMapRef:
              name: service-env
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.register.name }}-service"
spec:
  selector:
    {{- include "kioku.register.labels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: "hpa-{{ .Values.register.name }}-deployment"
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: "{{ .Values.register.name }}-deployment"
 minReplicas: {{ .Values.register.autoscaler.min }}
 maxReplicas: {{ .Values.register.autoscaler.max }}
 targetCPUUtilizationPercentage: {{ .Values.register.autoscaler.targetCPUUtilizationPercentage }}