apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
  labels:
    {{- include "kioku.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_HOST: {{ print .Values.database.databaseName "-pooler" | b64enc }}
  POSTGRES_USER: {{ print .Values.database.userName | b64enc }}
  POSTGRES_DB: {{ print .Values.database.databaseName | b64enc }}
  POSTGRES_PASSWORD: {{ print "password" | b64enc }}
  POSTGRES_PORT: {{ print 5432 | b64enc }}