apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
  labels:
    {{- include "kioku.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_HOST: {{ print .Values.database.name "-service" | b64enc }}
  POSTGRES_USER: user | base64
  POSTGRES_DB: database | base64
  POSTGRES_PASSWORD: password | base64
  POSTGRES_PORT: {{ print .Values.database.port | b64enc }}