name: Carddeck Service

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'backend/services/carddeck/**'
    - 'backend/store/**'

jobs:
  build-carddeck:
    uses: ./.github/workflows/build_service.yml
    with:
      image-name: kioku_carddeck
      path: ./backend/services/carddeck
      context: ./backend