name: Register Service

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'backend/services/register/**'

jobs:
  build-register:
    uses: ./.github/workflows/build_service.yml
    with:
      image-name: kioku_register
      path: ./backend/services/register
      context: ./backend