name: Build Production Images

on:
  workflow_dispatch:

jobs:
  build-frontend:
    uses: ./.github/workflows/build_service.yml
    with:
      image-name: kioku_frontend
      image-tag: prod
      path: ./frontend
      context: ./frontend

  build-register:
    uses: ./.github/workflows/build_service.yml
    with:
      image-name: kioku_register
      image-tag: prod
      path: ./backend/services/register
      context: ./backend
  
  build-login:
    uses: ./.github/workflows/build_service.yml
    with:
      image-name: kioku_login
      image-tag: prod
      path: ./backend/services/login
      context: ./backend
  
  build-frontend-proxy:
    uses: ./.github/workflows/build_service.yml
    with:
      image-name: kioku_frontend_proxy
      image-tag: prod
      path: ./backend/services/frontend
      context: ./backend