name: User Service

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'backend/services/user/**'
    - 'backend/store/**'

jobs:
  build-user:
    uses: ./.github/workflows/build_service.yml
    with:
      image-name: kioku_user
      path: ./backend/services/user
      context: ./backend